baseURL = 'https://lafirest.github.io'
languageCode = 'zh-CN'
title = 'Cogito, ergo sum'
paginate = 5
theme = "hugo-PaperMod"

[params]
    defaultTheme = "auto"
    disableThemeToggle = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    disableSpecial1stPost = true
    showtoc = true
    opentoc = true
    author = "firest"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30


